task_name: PC_rgr                 # name of fine-tuning benchmark, inlcuding
                                # classifications: ORD/PC
                                # regressions: ORD_rgr/PC_rgr
rxn_type:                       # for only PC/PC_rgr, you can select PC_rxn_type (list)
 - CN                           #CN/CO_90/CO_450/CP_bp  
 - CO_90
 - CO_450
# - CO_dp
fingerprint_type: morgan        # name of fingerprint: morgan              
model_type: RFR                 # model selection: RFR/Lasso/XGB/SVR
fingerprint: False              # use fingerprint
calc: True                     # use calculation data
n_splits: 2                    # numbaer of split in K-forld
trial_size: 100                    #Optuna trial size
evaluation_function: R2      #Evaluation function: classifier: acu/roc
                                                     #rgressor: R2/RMSE/MSE/RMSLE

dataset:
  #num_workers: 18                # dataloader number of workers
  valid_size: 0.0               # ratio of validation data
  test_size: 0.1                # ratio of test data
  #splitting: random          # data splitting (i.e., random/scaffold)
