#batch_size: 32                  # batch size
#epochs: 500                     # total number of epochs
#eval_every_n_epochs: 1          # validation frequency
#log_every_n_steps: 50           # print training log frequency
#init_lr: 0.0005                 # initial learning rate for the prediction head
#weight_decay: 1e-6              # weight decay of Adam
#gpu: cuda:0                     # training GPU
pick_h: False                    # picking h True/False
output: False                    # h output True/False
task_name: PC_rgr                  # name of fine-tuning benchmark, inlcuding
                                # classifications: ORD/PC
                                # regressions: ORD_rgr/PC_rgr
rxn_type:                       # for only PC/PC_rgr, you can select PC_rxn_type (list)
 - CN                           #CN/CO_90/CO_450/CP_bp  
# - CO_90
# - CO_450
# - CO_dp
fingerprint_type: morgan        # name of fingerprint: morgan
add_temp: False                 
model_type: XGB              # model selection: RFR/Lasso/XGB/SVR
best_model: True              #use best parameters
ORD_train: False               # use ORD data as train
fingerprint: False              # use fingerprint
calc: True                     # use calculation data
std: True                      # use standerized calculation data
try_num: 50                    # number of seed
train_test: True               # calulation train score
CV: True                       # cross validation
n_splits: 2                    # numbaer of split in K-forld
#model: 
  #num_layer: 5                  # number of graph conv layers
  #emb_dim: 300                  # embedding dimension in graph conv layers
  #feat_dim: 512                 # output feature dimention
  #drop_ratio: 0.3               # dropout ratio
  #pool: mean                    # readout pooling (i.e., mean/max/add)

dataset:
  #num_workers: 18                # dataloader number of workers
  valid_size: 0.0              # ratio of validation data
  test_size: 0.1                # ratio of test data
  #splitting: random          # data splitting (i.e., random/scaffold)

best:
  evaluation_function: R2      #Evaluation function: classifier: acu/roc
                                                     #rgressor: R2/RMSE/MSE/RMSLE
  trial_num: 452
  trial_date: 2304281059
